config/routes.rb
Lodoss::Application.routes.draw do

  get "pages/index"

  get "pages/contact"

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  #defaul router
  root :to => 'sessions#new'

  get "sessions/new"

  resources :users
  match '/signup',  :to => 'users#new'
  match '/edit', :to => 'users#update'
  match '/users/friends/:id', :to => 'users#friends'
  match '/users/search/:search', :to => 'users#search'
  match '/users/:pending/:id', :to => 'users#friends'
  match '/users/actionFriend'


  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/forgotpassword', :to => 'sessions#forgot_password'
  match '/newpassword/:hashlink', :to => 'sessions#new_password'
  match '/changepassword', :to => 'sessions#change_password'

  resources :comments
  match '/comments/side/:id', :to => 'comments#index'

  resources :messages
  match '/messages/chat/:id', :to => 'messages#chat'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

	attr_accessor   :password
	attr_accessible :email, :firstname, :lastname, :password, :password_confirmation, :avatar, :hashlink

  has_many :comments
  has_many :messages
  has_many :friendships

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, :presence   => true,
  				          :format     => { :with => email_regex },
  				          :uniqueness => { :case_sensitive => false }

	validates :password, :presence     => true,
  						         :confirmation => true,
  					 	         :length       => { :within => 6..40 },
                       :on           => :create

  before_save :encrypt_password

  mount_uploader :avatar, AvatarUploader

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  	
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
	end

  	private

	  	def encrypt_password
	  		self.salt = make_salt if new_record?
	  		self.encrypted_password = encrypt(password) if !password.nil?
	  	end

	  	def encrypt(string)
	  		secure_hash("#{salt}--#{string}")
	  	end

	  	def make_salt
	  		secure_hash("#{Time.now.utc}--#{password}")
	  	end

	  	def secure_hash(string)
	  		Digest::SHA2.hexdigest(string)
	  	end
end

app/controllers/users_controller.rb
class UsersController < LoginController

  def new
    if signed_in?
      redirect_to "/users/#{current_user.id}"
    else
      @title = "Sign up"
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      user = User.authenticate(params[:user][:email], params[:user][:password])
      sign_in user
      Friendship.create(:user_id => 1, :friend_id => user.id)
      redirect_to "/users/#{@user.id}"
    else
      # render :text => @user.errors.full_messages and return false
      flash[:alert] = @user.errors.full_messages
      redirect_to signup_path
    end
  end

	def show
    redirect_to root_path if current_user.nil?
    @user = User.find params[:id]
    if @user != current_user
      @current_friend = Friendship.where("(user_id = '#{@user.id}' AND friend_id = '#{current_user.id}') OR (user_id = '#{current_user.id}' AND friend_id = '#{@user.id}')").first
      if @current_friend.nil?
        @user[:status_friend] = "3"
      else
        @user[:status_friend] = @current_friend.accepted.nil? ? (@current_friend.user_id == current_user.id ? "2" : "0") : @current_friend.accepted
      end
    end
    respond_to do |format|
      format.html
      format.json { render :json => @user }
    end
  end

  def friends
    if params[:pending].nil?
      @users = Friendship
      .select('friendships.friend_id AS id, users.avatar, users.firstname, users.lastname')
      .joins('JOIN users ON friendships.friend_id = users.id')
      .where("friendships.accepted = 1 AND friendships.user_id = ?", params[:id])
    else
      @users = Friendship
      .select('friendships.user_id AS id, users.avatar, users.firstname, users.lastname')
      .joins('JOIN users ON friendships.user_id = users.id')
      .where("friendships.accepted IS NULL AND friendships.friend_id = ?", params[:id])
    end
    @users.each do |user_item|
      user = User.find user_item.id
      user_item.avatar = { :url => user.avatar.url }
    end
    render :json => @users
  end

  def actionFriend
    if params[:act] == "add"
      @user = User.find params[:id]
      @current_friend = Friendship.where("user_id = '#{@user.id}' AND friend_id = '#{current_user.id}'").first
      if !@current_friend.nil?
        Friendship.create(:friend_id => params[:id], :user_id => current_user.id, :accepted => 1)
        @current_friend.update_attributes(:accepted => 1)
      else
        Friendship.create(:user_id => current_user.id, :friend_id => params[:id])
      end
    else
      user_friend = Friendship.where("user_id = ?", current_user.id).find_by_friend_id params[:id]
      friend_user = Friendship.where("friend_id = ?", current_user.id).find_by_user_id params[:id]
      if !user_friend.nil?
        user_friend.delete
      end
      if !friend_user.nil?
        friend_user.delete
      end
    end
    render :json =>{ :result => "ok" }
  end

  def search
    query = "#{params[:search]}%"
    @users = User.where("id != ? AND (firstname like ? OR lastname like ? OR email like ?)", current_user.id, query, query, query).group
    respond_to do |format|
      format.html { render "show" }
      format.json { render :json => @users }
    end
  end

  def update
    @user = User.find current_user.id
    @message_bapass = 1
    if !params[:user].nil?
      if @user.update_attributes(params[:user])
        flash[:success] = "Profile success updated"
      else
        flash[:alert] = @user.errors.full_messages
      end
      #render :text => params[:user] and return false
      redirect_to '/edit'
    else
      render "edit"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="five columns centered">
  <%= form_for :user, :method => :put, :url => "/users/#{@user.id}", :multipart => true, :html => { 'id' => 'signup' } do |f| %>
    <%= render 'users/partials/error_messages' %>
    <fieldset>
      <legend>Edit Profile</legend>
      <div class="columns centered">
        <label>Firstname:</label>
        <%= f.text_field :firstname, {'type' => 'text', 'class' => 'seven'}  %>
      </div>
      <div class="columns centered">
        <label>Lastname:</label>
        <%= f.text_field :lastname, {'type' => 'text', 'class' => 'seven'}  %>
      </div>
      <div class="columns centered">
        <label>Avatar:</label>
        <%= image_tag @user.avatar_url %>
        <%= f.file_field :avatar %>
      </div>
      </br>
      <div class="columns centered">
        <%= f.submit "Edit", {'class' => 'radius button small'} %>
      </div>
      <br>
    </fieldset>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="five columns centered">
  <%= form_for :user, :url => '/users', :html => { 'id' => 'signup' } do |f| %>
    <%= render 'users/partials/error_messages' %>
    <fieldset>
      <legend>Registration Form</legend>
      <div class="columns centered">
        <%= f.email_field :email, {'placeholder' => 'Email', 'type' => 'text', 'class' => 'five'}  %>
      </div>
      <div class="columns centered">
        <%= f.text_field :firstname, {'placeholder' => 'Firstname', 'type' => 'text', 'class' => 'five'}  %>
      </div>
      <div class="columns centered">
        <%= f.text_field :lastname, {'placeholder' => 'Lastname', 'type' => 'text', 'class' => 'five'}  %>
      </div>
      <div class="columns centered">
        <%= f.password_field :password, {'placeholder' => 'Password', 'class' => 'five'} %>
      </div>
      <div class="columns centered">
        <%= f.password_field :password_confirmation, {'placeholder' => 'Confirm password', 'type' => 'password', 'class' => 'five'}  %>
      </div>
      <div class="columns centered">
        <%= f.submit "Signup", {'class' => 'radius button small'} %>
      </div>
      <br>
      <p><%= link_to "Sing In", signin_path, {"data-bypass" => "true"} %> 
        <span style="margin-left: 20px"><%= link_to "Forgot to password?", forgotpassword_path, {"data-bypass" => "true"} %></span>
      </p>
    </fieldset>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="user-box"></div>
<div id="chat-box"></div>
<div class="five columns centered" style="margin-bottom: 130px;"></div>
<div class="six columns centered" id='form-message'></div>